sudo: required
services:
  - docker # installs a copy of docker
before_install:
  - docker build -t lwalker5/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true lwalker5/docker-react npm run test
